// For getting buses
export const GET_BUSSES_REQUEST = "GET_BUSSES_REQUEST";
export const GET_BUSSES_REQUEST_SUCCESS = "GET_BUSSES_REQUEST_SUCCESS";
export const GET_BUSSES_REQUEST_FAILURE = "GET_BUSSES_REQUEST_FAILURE";

// For getting total buses
export const TOTAL_BUSSES_REQUEST = "TOTAL_BUSSES_REQUEST";
export const TOTAL_BUSSES_REQUEST_SUCCESS = "TOTAL_BUSSES_REQUEST_SUCCESS";
export const TOTAL_BUSSES_REQUEST_FAILURE = "TOTAL_BUSSES_REQUEST_FAILURE";

// For adding a new bus
export const ADD_NEW_BUS_REQUEST = "ADD_NEW_BUS_REQUEST";
export const ADD_NEW_BUS_SUCCESS = "ADD_NEW_BUS_SUCCESS";
export const ADD_NEW_BUS_FAILURE = "ADD_NEW_BUS_FAILURE";

// For deleting a bus
export const DELETE_BUS_REQUEST = "DELETE_BUS_REQUEST";
export const DELETE_BUS_SUCCESS = "DELETE_BUS_SUCCESS";
export const DELETE_BUS_FAILURE = "DELETE_BUS_FAILURE";

// For editing a bus
export const EDIT_BUS_REQUEST = "EDIT_BUS_REQUEST";
export const EDIT_BUS_SUCCESS = "EDIT_BUS_SUCCESS";
export const EDIT_BUS_FAILURE = "EDIT_BUS_FAILURE";
